#include "grad/transformer/metal_backend.h"
#include "grad/utils/env.h"
#include "metal_internal.h"

#include <algorithm>
#include <cstdint>
#include <cstdlib>
#include <mutex>
#include <new>
#include <stdexcept>
#include <string>
#include <vector>

namespace grad::metal {
namespace {

// Generated by CMake from metal_kernels.metal: kMetalKernelSource.
#include "metal_kernels.inc"

constexpr size_t kPageBytes = 16384;

bool page_aligned(const void* p) {
    return (reinterpret_cast<uintptr_t>(p) % kPageBytes) == 0;
}

size_t round_up_to_page(size_t n) {
    return ((n + kPageBytes - 1) / kPageBytes) * kPageBytes;
}

// fp32 -> fp16 conversion kernel for the CPU-mode offload, run on the GPU
// so operand halving costs one bandwidth-bound pass instead of a CPU round
// trip. Compiled from source at startup; if compilation fails the backend
// silently stays fp32.
constexpr const char* kConvertSource = R"(
#include <metal_stdlib>
using namespace metal;
kernel void f32_to_f16(device const float* src [[buffer(0)]],
                       device half* dst [[buffer(1)]],
                       uint i [[thread_position_in_grid]]) {
    dst[i] = half(src[i]);
}
)";

// One CPU-mode GPU job at a time. Calls from inside parallel_for regions are
// small (below the FLOP threshold) and never reach here.
std::mutex gpu_mutex;

// An MTLBuffer addressing p for bytes bytes: the pool block containing it,
// or else existing page-aligned memory wrapped without copying. Tensor
// storage is page-rounded (see tensor.cpp), so the rounded length stays
// within the allocation.
BufferRef wrap(id<MTLDevice> device, const void* p, size_t bytes) {
    BufferRef ref;
    if (pool().resolve(p, ref)) return ref;
    ref.buffer = [device newBufferWithBytesNoCopy:const_cast<void*>(p)
                                           length:round_up_to_page(bytes)
                                          options:MTLResourceStorageModeShared
                                      deallocator:nil];
    return ref;
}

MPSMatrix* make_matrix(const BufferRef& buf, size_t rows, size_t cols, MPSDataType dtype) {
    const size_t elem = (dtype == MPSDataTypeFloat16) ? 2 : sizeof(float);
    MPSMatrixDescriptor* desc = [MPSMatrixDescriptor matrixDescriptorWithRows:rows
                                                                      columns:cols
                                                                     rowBytes:cols * elem
                                                                     dataType:dtype];
    return [[MPSMatrix alloc] initWithBuffer:buf.buffer offset:buf.offset descriptor:desc];
}

id<MTLBuffer> scratch_fp16(Context& c, int slot, size_t elements) {
    const size_t bytes = elements * 2;
    if (c.scratch_cap[slot] < bytes) {
        c.scratch[slot] = [c.device newBufferWithLength:bytes
                                                options:MTLResourceStorageModePrivate];
        c.scratch_cap[slot] = c.scratch[slot] ? bytes : 0;
    }
    return c.scratch[slot];
}

// The xorshift128+ state (s0, s1) as 128 bits over GF(2), s0 in bits 0-63.
// Row r of a matrix is two words, the masks of s0 and s1 bits whose parity
// is output bit r, so one step of the generator is a matrix-vector product
// and T^k jumps k steps ahead.
using Gf2Matrix = std::array<uint64_t, 256>;

bool gf2_bit(const Gf2Matrix& m, size_t row, size_t col) {
    return ((m[2 * row + col / 64] >> (col % 64)) & 1u) != 0;
}

Gf2Matrix gf2_multiply(const Gf2Matrix& a, const Gf2Matrix& b) {
    Gf2Matrix c{};
    for (size_t r = 0; r < 128; r++) {
        for (size_t k = 0; k < 128; k++) {
            if (gf2_bit(a, r, k)) {
                c[2 * r] ^= b[2 * k];
                c[2 * r + 1] ^= b[2 * k + 1];
            }
        }
    }
    return c;
}

// The matrix of one xorshift128+ step as activations.cpp takes it: s0' = s1,
// s1' = x ^ s1 ^ (x >> 17) ^ (s1 >> 26) with x = s0 ^ (s0 << 23). Column c
// is the step applied to the unit state with only bit c set.
Gf2Matrix xorshift_step_matrix() {
    Gf2Matrix t{};
    for (size_t c = 0; c < 128; c++) {
        const uint64_t s0 = c < 64 ? uint64_t{1} << c : 0;
        const uint64_t s1 = c >= 64 ? uint64_t{1} << (c - 64) : 0;
        uint64_t x = s0;
        x ^= x << 23;
        const uint64_t out[2] = {s1, x ^ s1 ^ (x >> 17) ^ (s1 >> 26)};
        for (size_t r = 0; r < 128; r++) {
            if ((out[r / 64] >> (r % 64)) & 1u) t[2 * r + c / 64] |= uint64_t{1} << (c % 64);
        }
    }
    return t;
}

// jump[k] = T^(64k) for the 256 threads that share a 65,536-element dropout
// block (4 lanes per step, so 16,384 steps, 64 per thread).
std::vector<uint64_t> dropout_jump_matrices() {
    Gf2Matrix step = xorshift_step_matrix();
    for (int i = 0; i < 6; i++) step = gf2_multiply(step, step);  // T^64
    Gf2Matrix jump{};
    for (size_t r = 0; r < 128; r++) jump[2 * r + r / 64] = uint64_t{1} << (r % 64);  // identity
    std::vector<uint64_t> all;
    all.reserve(256 * jump.size());
    for (int k = 0; k < 256; k++) {
        all.insert(all.end(), jump.begin(), jump.end());
        jump = gf2_multiply(step, jump);
    }
    return all;
}

// Safe math: IEEE semantics for NaN and infinity, no reassociation, and
// precise transcendentals, so GPU results track the CPU's to rounding.
MTLCompileOptions* resident_compile_options() {
    MTLCompileOptions* options = [[MTLCompileOptions alloc] init];
    if (@available(macOS 15.0, *)) {
        options.mathMode = MTLMathModeSafe;
    } else {
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
        options.fastMathEnabled = NO;
#pragma clang diagnostic pop
    }
    return options;
}

}  // namespace

// ------------------------------------------------------------------- context

Context::Context() {
    if (const char* value = env::lookup("GRAD_METAL", "TRANSFORMER_METAL")) {
        if (value[0] == '0') return;
    }
    device = MTLCreateSystemDefaultDevice();
    if (!device) return;
    // Unified memory is the whole premise: without it we would need real
    // transfers and a very different design.
    if (![device hasUnifiedMemory]) return;
    queue = [device newCommandQueue];
    ok = (queue != nil);
    if (!ok) return;

    // Off by default: measured at the current model scale, fp16 operands
    // neither help (logits matmuls: bandwidth win cancels conversion cost)
    // nor let smaller matmuls win on the GPU (FFN at a 5 GFLOP threshold ran
    // 14% slower - synchronous dispatch still loses to AMX). See
    // BENCHMARKS.md #11. The machinery stays for the next model size up,
    // where the GPU's margin grows.
    bool want_fp16 = false;
    if (const char* value = env::lookup("GRAD_METAL_FP16", "TRANSFORMER_METAL_FP16")) {
        if (value[0] == '1') want_fp16 = true;
    }
    if (want_fp16) {
        NSError* error = nil;
        id<MTLLibrary> lib = [device newLibraryWithSource:@(kConvertSource)
                                                  options:nil
                                                    error:&error];
        id<MTLFunction> fn = lib ? [lib newFunctionWithName:@"f32_to_f16"] : nil;
        convert = fn ? [device newComputePipelineStateWithFunction:fn error:&error] : nil;
        fp16 = (convert != nil);
    }
}

void Context::init_resident() {
    std::call_once(resident_once, [this] {
        if (!ok) {
            resident_status = "no Metal device with unified memory (or GRAD_METAL=0)";
            return;
        }
        // The batched GEMM is built on simdgroup matrices (Apple GPU
        // family 7, the M1 generation, and later).
        if (![device supportsFamily:MTLGPUFamilyApple7]) {
            resident_status = "GPU predates Apple family 7 (simdgroup matrices)";
            return;
        }
        @autoreleasepool {
            NSString* source = [[NSString alloc] initWithBytes:kMetalKernelSource
                                                        length:sizeof(kMetalKernelSource) - 1
                                                      encoding:NSASCIIStringEncoding];
            NSError* error = nil;
            id<MTLLibrary> lib = [device newLibraryWithSource:source
                                                      options:resident_compile_options()
                                                        error:&error];
            if (!lib) {
                resident_status = std::string("kernel compilation failed: ")
                                  + (error ? [[error localizedDescription] UTF8String] : "unknown");
                return;
            }
            for (size_t k = 0; k < kKernels.size(); k++) {
                id<MTLFunction> fn = [lib newFunctionWithName:@(kKernels[k].name)];
                id<MTLComputePipelineState> pso =
                    fn ? [device newComputePipelineStateWithFunction:fn error:&error] : nil;
                if (!pso) {
                    resident_status = std::string("cannot build kernel ") + kKernels[k].name;
                    return;
                }
                if (kKernels[k].threads > pso.maxTotalThreadsPerThreadgroup) {
                    resident_status = std::string("kernel ") + kKernels[k].name + " needs "
                                      + std::to_string(kKernels[k].threads)
                                      + " threads per threadgroup";
                    return;
                }
                pipelines[k] = pso;
            }
            const std::vector<uint64_t> jumps = dropout_jump_matrices();
            dropout_jumps = [device newBufferWithBytes:jumps.data()
                                                length:jumps.size() * sizeof(uint64_t)
                                               options:MTLResourceStorageModeShared];
            if (!dropout_jumps) {
                resident_status = "cannot allocate the dropout jump table";
                return;
            }
        }
        resident_ok = true;
        resident_status = "ok";
    });
}

Context& ctx() {
    static Context c;
    return c;
}

// ---------------------------------------------------------------------- pool

float* Pool::allocate(size_t bytes) {
    const size_t size = round_up_to_page(std::max<size_t>(bytes, 1));
    {
        std::lock_guard<std::mutex> lk(mu_);
        auto it = free_.find(size);
        if (it != free_.end() && !it->second.empty()) {
            float* base = it->second.back();
            it->second.pop_back();
            blocks_.at(base).live = true;
            live_bytes_ += size;
            peak_live_bytes_ = std::max(peak_live_bytes_, live_bytes_);
            return base;
        }
    }
    id<MTLBuffer> buffer = nil;
    @autoreleasepool {
        buffer = [ctx().device newBufferWithLength:size options:MTLResourceStorageModeShared];
    }
    if (!buffer) throw std::bad_alloc();
    auto* base = static_cast<float*>([buffer contents]);
    std::lock_guard<std::mutex> lk(mu_);
    Block& block = blocks_[base];
    block.buffer = buffer;
    block.data = base;
    block.size = size;
    block.live = true;
    live_bytes_ += size;
    cached_bytes_ += size;
    peak_live_bytes_ = std::max(peak_live_bytes_, live_bytes_);
    return base;
}

void Pool::make_free_locked(Block& block) {
    block.tag = 0;
    free_[block.size].push_back(block.data);
}

void Pool::release(const float* p) noexcept {
    if (!p) return;
    const Stream& s = stream();
    const bool idle = s.idle();
    const uint64_t tag = s.current_seq();
    try {
        std::lock_guard<std::mutex> lk(mu_);
        auto it = blocks_.find(p);
        if (it == blocks_.end() || !it->second.live) return;  // not ours: nothing to do
        Block& block = it->second;
        block.live = false;
        live_bytes_ -= block.size;
        if (idle) {
            make_free_locked(block);
        } else {
            block.tag = tag;
            deferred_.push_back(block.data);
        }
    } catch (...) {
        // Only a failed allocation growing a free list lands here. The
        // block then stays out of circulation, which is safe (queued work
        // may still read it) and merely costs its memory.
        leaked_blocks_.fetch_add(1, std::memory_order_relaxed);
    }
}

bool Pool::resolve(const void* p, BufferRef& out) {
    std::lock_guard<std::mutex> lk(mu_);
    auto it = blocks_.upper_bound(static_cast<const float*>(p));
    if (it == blocks_.begin()) return false;
    --it;
    const size_t offset = reinterpret_cast<uintptr_t>(p) - reinterpret_cast<uintptr_t>(it->first);
    if (offset >= it->second.size) return false;
    out.buffer = it->second.buffer;
    out.offset = offset;
    return true;
}

void Pool::reclaim(uint64_t completed_seq) {
    std::lock_guard<std::mutex> lk(mu_);
    auto keep = deferred_.begin();
    for (float* base : deferred_) {
        Block& block = blocks_.at(base);
        if (block.tag <= completed_seq) {
            make_free_locked(block);
        } else {
            *keep++ = base;
        }
    }
    deferred_.erase(keep, deferred_.end());
}

void Pool::reclaim_all() {
    std::lock_guard<std::mutex> lk(mu_);
    for (float* base : deferred_) make_free_locked(blocks_.at(base));
    deferred_.clear();
}

void Pool::empty_cache() {
    std::lock_guard<std::mutex> lk(mu_);
    for (auto& [size, bases] : free_) {
        for (float* base : bases) {
            cached_bytes_ -= size;
            blocks_.erase(base);
        }
    }
    free_.clear();
}

void Pool::add_stats(size_t& live, size_t& peak, size_t& cached) {
    std::lock_guard<std::mutex> lk(mu_);
    live = live_bytes_;
    peak = peak_live_bytes_;
    cached = cached_bytes_;
}

// Never destroyed: a Tensor released during static destruction (a global,
// or a pool thread's cache) must still find the pool and the stream.
Pool& pool() {
    static Pool* p = new Pool;
    return *p;
}

// -------------------------------------------------------------------- stream

Stream::Stream() {
    // 32 dispatches is ~0.2 ms of encoding at ~5 us each: the longest the
    // GPU waits for its first work after a sync, while the ~10-30 us cost of
    // a commit stays under a tenth of the encoding time it covers.
    if (const char* value = std::getenv("GRAD_METAL_COMMIT")) {
        const long n = std::atol(value);
        if (n > 0) commit_every_ = static_cast<size_t>(n);
    }
    // Storage released while its command buffer is queued is reused only
    // once that buffer completes, so memory grows with how far the CPU runs
    // ahead of the GPU. 16 buffers of 32 dispatches is about half a 70M
    // micro-batch of lead (~1,000 dispatches each): enough queued work to
    // keep the GPU busy, and a bounded addition to peak memory.
    if (const char* value = std::getenv("GRAD_METAL_MAX_IN_FLIGHT")) {
        const long n = std::atol(value);
        if (n > 0) max_in_flight_ = static_cast<size_t>(n);
    }
}

bool Stream::open_locked() {
    if (cb_) return true;
    cb_ = [ctx().queue commandBuffer];
    return cb_ != nil;
}

void Stream::end_encoder_locked() {
    if (enc_) {
        [enc_ endEncoding];
        enc_ = nil;
    }
}

void Stream::dispatched_locked() {
    ++open_dispatches_;
    has_open_work_.store(true, std::memory_order_relaxed);
    pending_.store(true, std::memory_order_relaxed);
    dispatches_.fetch_add(1, std::memory_order_relaxed);
    if (open_dispatches_ >= commit_every_) commit_locked();
}

void Stream::fail_open() {
    if (error_.empty()) error_ = "could not create a Metal command buffer or encoder";
    pending_.store(true, std::memory_order_relaxed);
}

void Stream::commit_locked() {
    if (!cb_) return;
    end_encoder_locked();
    if (open_dispatches_ == 0) return;  // keep the empty buffer open for the next dispatch
    const uint64_t seq = open_seq_.load(std::memory_order_relaxed);
    std::atomic<uint64_t>* completed = &completed_seq_;
    [cb_ addCompletedHandler:^(id<MTLCommandBuffer>) {
      uint64_t prev = completed->load(std::memory_order_relaxed);
      while (prev < seq && !completed->compare_exchange_weak(prev, seq)) {
      }
      pool().reclaim(seq);
    }];
    [cb_ commit];
    in_flight_.push_back(cb_);
    cb_ = nil;
    open_dispatches_ = 0;
    has_open_work_.store(false, std::memory_order_relaxed);
    open_seq_.store(seq + 1, std::memory_order_relaxed);
    command_buffers_.fetch_add(1, std::memory_order_relaxed);
    throttle_locked();
}

void Stream::throttle_locked() {
    // Completed buffers are dropped first, so a caller that never syncs does
    // not accumulate them; a failure among them waits in error_ for the
    // next sync. What remains is (nearly) the work the GPU has not done.
    const auto drain = [this] {
        const std::string failure = drain_errors_locked(false);
        if (error_.empty()) error_ = failure;
    };
    drain();
    while (in_flight_.size() > max_in_flight_) {
        [in_flight_.front() waitUntilCompleted];
        throttle_waits_.fetch_add(1, std::memory_order_relaxed);
        drain();
    }
}

std::string Stream::drain_errors_locked(bool all) {
    std::string failure;
    while (!in_flight_.empty()) {
        id<MTLCommandBuffer> cb = in_flight_.front();
        const MTLCommandBufferStatus status = cb.status;
        if (!all && status != MTLCommandBufferStatusCompleted
            && status != MTLCommandBufferStatusError) {
            break;
        }
        if (status == MTLCommandBufferStatusError && failure.empty()) {
            NSError* err = cb.error;
            failure = err ? std::string([[err localizedDescription] UTF8String])
                          : std::string("command buffer failed");
        }
        in_flight_.pop_front();
    }
    return failure;
}

void Stream::synchronize() {
    std::string failure;
    {
        std::lock_guard<std::mutex> lk(mu_);
        @autoreleasepool {
            commit_locked();
            if (!in_flight_.empty()) [in_flight_.back() waitUntilCompleted];
            // Every buffer has completed, so every deferred block is free,
            // including those tagged with a buffer that was never committed.
            completed_seq_.store(open_seq_.load(std::memory_order_relaxed) - 1,
                                 std::memory_order_relaxed);
            pool().reclaim_all();
            failure = drain_errors_locked(true);
            if (failure.empty()) failure = error_;
            error_.clear();
        }
        pending_.store(false, std::memory_order_relaxed);
        syncs_.fetch_add(1, std::memory_order_relaxed);
    }
    if (!failure.empty()) {
        throw std::runtime_error("Metal command buffer failed: " + failure);
    }
}

void Stream::fence() {
    if (pending_.load(std::memory_order_relaxed)) synchronize();
}

void Stream::flush() {
    std::lock_guard<std::mutex> lk(mu_);
    @autoreleasepool {
        commit_locked();
    }
}

bool Stream::idle() const {
    return !has_open_work_.load(std::memory_order_relaxed)
           && completed_seq_.load(std::memory_order_relaxed) + 1
                  >= open_seq_.load(std::memory_order_relaxed);
}

uint64_t Stream::current_seq() const {
    const uint64_t open = open_seq_.load(std::memory_order_relaxed);
    return has_open_work_.load(std::memory_order_relaxed) ? open : open - 1;
}

void Stream::add_stats(StreamStats& out) const {
    out.syncs = syncs_.load(std::memory_order_relaxed);
    out.command_buffers = command_buffers_.load(std::memory_order_relaxed);
    out.dispatches = dispatches_.load(std::memory_order_relaxed);
    out.throttle_waits = throttle_waits_.load(std::memory_order_relaxed);
}

Stream& stream() {
    static Stream* s = new Stream;
    return *s;
}

// ---------------------------------------------------------------- public API

bool available() {
    return ctx().ok;
}

bool fp16_active() {
    return ctx().ok && ctx().fp16;
}

bool resident_available() {
    Context& c = ctx();
    c.init_resident();
    return c.resident_ok;
}

std::string resident_status() {
    Context& c = ctx();
    c.init_resident();
    return c.resident_status;
}

void fence() {
    stream().fence();
}

void synchronize() {
    stream().synchronize();
}

void flush() {
    stream().flush();
}

StreamStats stream_stats() {
    StreamStats out;
    stream().add_stats(out);
    pool().add_stats(out.live_bytes, out.peak_live_bytes, out.cached_bytes);
    return out;
}

float* allocate(size_t bytes) {
    return pool().allocate(bytes);
}

void release(const float* p) noexcept {
    pool().release(p);
}

void empty_cache() {
    synchronize();
    pool().empty_cache();
}

bool sgemm(const float* A, const float* B, float* C, size_t M, size_t N, size_t K, bool transA,
           bool transB, float alpha, float beta) {
    Context& c = ctx();
    if (!c.ok) return false;
    if (!page_aligned(A) || !page_aligned(B) || !page_aligned(C)) return false;
    // A synchronous call from CPU code: nothing it reads may still be queued
    // in the resident stream. A no-op in CPU mode, where nothing is queued.
    fence();

    const size_t a_rows = transA ? K : M;
    const size_t a_cols = transA ? M : K;
    const size_t b_rows = transB ? N : K;
    const size_t b_cols = transB ? K : N;
    const size_t nA = a_rows * a_cols;
    const size_t nB = b_rows * b_cols;

    // Every early return below happens before commit, when nothing has
    // been submitted and C is untouched, so the caller's CPU fallback is
    // safe. Once committed, the GPU may have written part of C (and with
    // beta != 0 consumed its old contents), so a failure there cannot be
    // retried and is thrown instead - outside the autorelease pool, which
    // is not drained by C++ unwinding.
    std::string failure;
    @autoreleasepool {
        std::lock_guard<std::mutex> lk(gpu_mutex);

        const BufferRef bufA = wrap(c.device, A, nA * sizeof(float));
        const BufferRef bufB = wrap(c.device, B, nB * sizeof(float));
        const BufferRef bufC = wrap(c.device, C, M * N * sizeof(float));
        if (!bufA.buffer || !bufB.buffer || !bufC.buffer) return false;

        id<MTLBuffer> halfA = nil;
        id<MTLBuffer> halfB = nil;
        if (c.fp16) {
            halfA = scratch_fp16(c, 0, nA);
            halfB = scratch_fp16(c, 1, nB);
        }
        const bool use_fp16 = (halfA != nil && halfB != nil);

        MPSMatrixMultiplication* mm = [[MPSMatrixMultiplication alloc] initWithDevice:c.device
                                                                        transposeLeft:transA
                                                                       transposeRight:transB
                                                                           resultRows:M
                                                                        resultColumns:N
                                                                      interiorColumns:K
                                                                                alpha:alpha
                                                                                 beta:beta];
        if (!mm) return false;

        id<MTLCommandBuffer> cb = [c.queue commandBuffer];
        if (!cb) return false;

        if (use_fp16) {
            // Halve the operands on-device, then multiply fp16 x fp16 with
            // an fp32 result matrix: MPS accumulates (and applies
            // alpha/beta) in full precision.
            id<MTLComputeCommandEncoder> enc = [cb computeCommandEncoder];
            if (!enc) return false;  // messages to nil would skip the conversion
            [enc setComputePipelineState:c.convert];
            const NSUInteger tg = c.convert.maxTotalThreadsPerThreadgroup;
            [enc setBuffer:bufA.buffer offset:bufA.offset atIndex:0];
            [enc setBuffer:halfA offset:0 atIndex:1];
            [enc dispatchThreads:MTLSizeMake(nA, 1, 1)
                threadsPerThreadgroup:MTLSizeMake(tg < 256 ? tg : 256, 1, 1)];
            [enc setBuffer:bufB.buffer offset:bufB.offset atIndex:0];
            [enc setBuffer:halfB offset:0 atIndex:1];
            [enc dispatchThreads:MTLSizeMake(nB, 1, 1)
                threadsPerThreadgroup:MTLSizeMake(tg < 256 ? tg : 256, 1, 1)];
            [enc endEncoding];

            [mm encodeToCommandBuffer:cb
                           leftMatrix:make_matrix({halfA, 0}, a_rows, a_cols, MPSDataTypeFloat16)
                          rightMatrix:make_matrix({halfB, 0}, b_rows, b_cols, MPSDataTypeFloat16)
                         resultMatrix:make_matrix(bufC, M, N, MPSDataTypeFloat32)];
        } else {
            [mm encodeToCommandBuffer:cb
                           leftMatrix:make_matrix(bufA, a_rows, a_cols, MPSDataTypeFloat32)
                          rightMatrix:make_matrix(bufB, b_rows, b_cols, MPSDataTypeFloat32)
                         resultMatrix:make_matrix(bufC, M, N, MPSDataTypeFloat32)];
        }
        [cb commit];
        [cb waitUntilCompleted];

        if (cb.status != MTLCommandBufferStatusCompleted) {
            NSError* err = cb.error;
            failure = err ? std::string([[err localizedDescription] UTF8String])
                          : std::string("status ") + std::to_string(static_cast<long>(cb.status));
        }
    }
    if (!failure.empty()) {
        throw std::runtime_error("Metal sgemm failed after submission (C may be partially "
                                 "written, so it cannot fall back to the CPU): "
                                 + failure);
    }
    return true;
}

}  // namespace grad::metal
