#!/usr/bin/env python3
"""Generates src/tokenizer/unicode_tables.h, the \\p{L} and \\p{N} code point
ranges the v2 pre-tokenizer classifies with.

    python3 tools/gen_unicode_tables.py > src/tokenizer/unicode_tables.h

The ranges come from this Python's unicodedata module; the header records its
Unicode version. Regenerating with a newer Python changes which code points
count as letters or numbers, which changes how ByteBpe pre-tokenizes, so it
must come with a new pre-tokenizer id (see pretokenize.h) rather than replace
the tables in place.
"""

import sys
import unicodedata


def ranges(predicate):
    out = []
    start = None
    for cp in range(0x110000):
        hit = predicate(cp)
        if hit and start is None:
            start = cp
        elif not hit and start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, 0x10FFFF))
    return out


def category(cp):
    return unicodedata.category(chr(cp))


def emit(name, table):
    print("// clang-format off")
    print(f"inline constexpr CodepointRange {name}[] = {{")
    for lo, hi in table:
        print(f"    {{0x{lo:04X}, 0x{hi:04X}}},")
    print("};")
    print("// clang-format on")


def main():
    letters = ranges(lambda cp: category(cp).startswith("L"))
    numbers = ranges(lambda cp: category(cp).startswith("N"))
    print("#pragma once")
    print()
    print("// Generated by tools/gen_unicode_tables.py from Unicode "
          f"{unicodedata.unidata_version}; do not edit.")
    print("// \\p{L} is general category L* (Lu Ll Lt Lm Lo), \\p{N} is N* "
          "(Nd Nl No).")
    print("// Sorted, disjoint, inclusive ranges.")
    print()
    print("#include <cstdint>")
    print()
    print("namespace grad::unicode {")
    print()
    print("struct CodepointRange {")
    print("    std::uint32_t lo;")
    print("    std::uint32_t hi;")
    print("};")
    print()
    print(f'inline constexpr const char* kUnicodeVersion = "{unicodedata.unidata_version}";')
    print()
    emit("kLetterRanges", letters)
    print()
    emit("kNumberRanges", numbers)
    print()
    print("}  // namespace grad::unicode")
    print(f"{len(letters)} letter and {len(numbers)} number ranges", file=sys.stderr)


if __name__ == "__main__":
    main()
